name: Deployment

on:
  push:
    branches:
      - master

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set yarn cache
      uses: c-hive/gha-yarn-cache@v2

    - name: Initialize
      run: make github-action-init

    - name: Blocklet workflow
      uses: blocklet/action-workflow@v0.2.2
      with:
        skip-deploy: false
        bundle-command: yarn build
        abtnode-endpoint: ${{ secrets.AWS_NODE_ENDPOINT }}
        access-key: ${{ secrets.AWS_NODE_ACCESS_KEY }}
        access-secret: ${{ secrets.AWS_NODE_ACCESS_SECRET }}
        slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
