name: Deployment

on:
  push:
    branches:
      - master

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Initialize
      run: make github-action-init

    - name: Deploy
      env:
        AWS_NODE_ENDPOINT: ${{ secrets.AWS_NODE_ENDPOINT }}
        AWS_NODE_ACCESS_KEY: ${{ secrets.AWS_NODE_ACCESS_KEY }}
        AWS_NODE_ACCESS_SECRET: ${{ secrets.AWS_NODE_ACCESS_SECRET }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: bash ./tools/publish.sh

    - name: Release to Github
      uses: blocklet/action-release-to-github@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
